#!/usr/bin/env python3
"""Rebuild manifest.json from a fresh Sanity inventory.

The Sanity read is done by a Claude through the Sanity MCP (see
sanity_urls.groq), not by this script, so that CI never needs Sanity
credentials. The Claude saves the rows as `COURSE|URL` lines and runs:

    python3 scripts/build_manifest.py --rows rows.txt

Hand-tuned `expect` blocks on existing pages are preserved. Pages that have
dropped out of Sanity are kept but marked `"retired": true` rather than
deleted, so an unwiring that was a mistake stays visible.
"""
import argparse, collections, datetime, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def slug(url: str) -> str:
    s = url.split('://', 1)[-1].split('/', 1)[-1].rstrip('/') or 'root'
    return s.replace('/', '_').replace('?', '-').replace('=', '').replace('&', '-')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--rows', required=True, help='file of COURSE|URL lines')
    ap.add_argument('--manifest', default=os.path.join(ROOT, 'manifest.json'))
    ap.add_argument('--owner', default='swachtel-dev')
    ap.add_argument('--dry-run', action='store_true')
    a = ap.parse_args()

    by_url = collections.OrderedDict()
    for line in open(a.rows):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        course, _, url = line.partition('|')
        if not url:
            print(f'skipping malformed row: {line}', file=sys.stderr)
            continue
        by_url.setdefault(url.strip(), set()).add(course.strip())

    old = {}
    if os.path.exists(a.manifest):
        old = {p['url']: p for p in json.load(open(a.manifest)).get('pages', [])}

    pages = []
    for url, courses in by_url.items():
        prev = old.get(url, {})
        pages.append({
            'id': prev.get('id') or slug(url),
            'url': url,
            'courses': sorted(courses),
            'owner': prev.get('owner', a.owner),
            'source': 'sanity:production',
            'expect': prev.get('expect', {'minVisibleText': 300}),
        })
    retired = [dict(p, retired=True, courses=[]) for u, p in old.items()
               if u not in by_url and not p.get('retired')]
    pages.extend(retired)

    out = {
        '_comment': ('Generated by scripts/build_manifest.py. Edit an `expect` block by hand to '
                     'tighten a page; regeneration preserves it. `retired: true` means the page is '
                     'no longer referenced by live course content.'),
        'generated': datetime.date.today().isoformat(),
        'pages': pages,
    }
    added = [u for u in by_url if u not in old]
    dropped = [p['url'] for p in retired]
    print(f'{len(pages)} pages ({len(added)} new, {len(dropped)} newly retired)')
    for u in added:
        print(f'  + {u}')
    for u in dropped:
        print(f'  - {u}  (no longer referenced in Sanity)')
    if a.dry_run:
        return 0
    json.dump(out, open(a.manifest, 'w'), indent=2)
    print(f'wrote {a.manifest}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
